#!/bin/bash
#
# test to print error message is command is not found

command="Invalid_command_that_does_not_exist"
tmp_file="checker_tmp_file_$RANDOM"

# create output file to help debug
save_file=$(echo $BASH_SOURCE | sed -e 's/\.\///g' -e 's/\//_/g')

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file

# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# copy saved output for debugging
cat $OUTPUTFILE > "$SAVEOUTPUTDIR/$save_file"

# check the result
nmatch=`cat $OUTPUTFILE | grep -c ": 1: Invalid_command_that_does_not_exist: not found"`
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
